name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Copy files to EC2
      run: |
        scp -o StrictHostKeyChecking=no -r . ubuntu@23.21.4.208/home/ubuntu/nestjs

    - name: SSH and deploy
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@23.21.4.208 << 'EOF'
        cd /home/ubuntu/nestjs
        npm install
        npm run build
        npm run start
        
        EOF
